crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('client/', include('client.urls', namespace='client')),
    path('main/', include('office.urls', namespace='office')),
    path('', include('portal.urls', namespace='portal')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

admin.site.site_header = 'پورتال شرکت نمایشگاه بین‌المللی ارومیه'

office/urls.py
from django.urls import path
from .views import *

app_name = "office"

urlpatterns = [
    path('', Test.as_view(), name='test'),
    path('home/', HomeView.as_view(), name='home'),
    path('user/add/', UserAddView.as_view(), name='user-add'),
    path('customer/list/', CustomerListView.as_view(), name='customer-list'),
    path('deactive/customer/list/', DeactiveCustomerListView.as_view(), name='deactive-customer-list'),
    path('profile/accept/<int:pid>/', ProfileAcceptView.as_view(), name='profile-accept'),
    path('profile/deny/<int:pid>/', ProfileDenyView.as_view(), name='profile-deny'),
    path('customer/add/', CustomerAddView.as_view(), name='customer-add'),
    path('customer/change/<int:cid>/', CustomerChangeView.as_view(), name='customer-change'),
    path('customer/exhibition/<int:id>/', CustomerExhibitionView.as_view(), name='customer-exhibition'),
    path('customer/exhibition/edit/<int:id>/', CustomerExhibitionEditView.as_view(), name='customer-exhibition-edit'),
    path('request/list/', RequestListView.as_view(), name='request-list'),
    path('request/state/<int:rid>/', RequestStateView.as_view(), name='request-state'),
    path('invoice/list/', InvoiceListView.as_view(), name='invoice-list'),
    path('invoice/remove/<int:iid>/', InvoiceRemoveView.as_view(), name='invoice-remove'),
    path('invoice/edit/<int:iid>/', InvoiceEditView.as_view(), name='invoice-edit'),
    path('document/list/<int:cid>/', DocumentListView.as_view(), name='document-list'),
    path('document/add/<int:id>/', DocumentsAddView.as_view(), name='documents-add'),
    path('document/del/<int:fid>/', DocumentsDelView.as_view(), name='documents-del'),
    path('document/accept/<int:fid>/', DocumentsAcceptView.as_view(), name='documents-accept'),
    path('document/deny/<int:fid>/', DocumentsDenyView.as_view(), name='documents-deny'),
    # path('message/list/', MessagesListView.as_view(), name='message-list'),
    # path('message/add/', MessageAddView.as_view(), name='message-add'),
    # path('message/change/<int:mid>/', MessageChangeView.as_view(), name='message-change'),
    path('exhibition/add/', ExhibitionAddView.as_view(), name='exhibition-add'),
    path('exhibition/list/', ExhibitionListView.as_view(), name='exhibition-list'),
    path('exhibition/details/<int:eid>/', ExhibitionDetailsView.as_view(), name='exhibition-details'),
    path('exhibition/details/<int:eid>/<int:iid>/', ExhibitionDetailsEditView.as_view(), name='exhibition-details-edit'),
    path('exhibition/status/<int:id>/', ExhibitionStatusView.as_view(), name='exhibition-status'),
    path('payment/list/', PaymentListView.as_view(), name='payment-list'),
    path('payment/add/<int:iid>/', PaymentAddView.as_view(), name='payment-add'),
    path('payment/remove/<int:pid>/', PaymentRemoveView.as_view(), name='payment-remove'),
    path('payment/edit/<int:iid>/<int:pid>/', PaymentEditView.as_view(), name='payment-edit'),
    path('payment/checkout/<int:iid>/', CheckoutView.as_view(), name='checkout'),
    path('payment/checkout/invoice/<int:iid>/', InvoicePrintView.as_view(), name='invoice-print'),
    path('payment/exit/permit/<int:iid>/', ExitPermitView.as_view(), name='exit-permit'),
    # path('payment/deposit/add/', DepositAddView.as_view(), name='deposit-add'),
    # path('payment/deposit/state/<int:did>/', DepositStateAddView.as_view(), name='deposit-state-add'),
    # path('payment/deposit/list/', DepositListView.as_view(), name='deposit-list'),
    ]

office/forms.py
from django import forms
from .models import *
from client.models import *
from django.core.exceptions import ValidationError
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget

def is_code(value):
    if len(value) != 10 or not str(value).isnumeric():
        raise ValidationError('کد ملی صحیح نمی‌باشد!')
    
def is_mobile(value):
    if not str(value).isnumeric() or len(value) !=11 or str(value)[0] != '0':
        raise ValidationError('شماره موبایل صحیح نمی‌باشد!')
    
def is_phone(value):
    if not str(value).isnumeric() or len(value) !=11 or str(value)[0] != '0':
        raise ValidationError('شماره تلفن صحیح نمی‌باشد!')
    
def is_ncode(value):
    if len(value) != 11 or not str(value).isnumeric():
        raise ValidationError("شناسه ملی صحیح نمی‌باشد.")
    
def is_postal(value):
    if len(value) != 10 or not str(value).isnumeric():
        raise ValidationError('کد پستی صحیح نمی‌باشد!')
    
def is_positive(value):
    if not str(value).isnumeric():
        raise ValidationError('لطفاً فقط عدد وارد کنید!')
    if str(value).isnumeric():
        if int(value) < 1:
            raise ValidationError('عدد باید بزرگتر از صفر باشد!')
        
def is_discount(value):
    if not str(value).isnumeric():
        raise ValidationError('لطفاً فقط عدد وارد کنید!')
    if str(value).isnumeric():
        if int(value) < 0:
            raise ValidationError('کمترین مقدار می‌تواند عدد صفر باشد!')
        
def validate_file_size(value):
    filesize = value.size
    if filesize > 4194304:  # 10MB limit
        raise ValidationError("حجم فایل مورد نظر بیشتر از 4 مگابایت می‌باشد")
    return value

        

class UserAddForm(forms.Form):
    is_active = forms.BooleanField(label="فعال",required=False, widget=forms.CheckboxInput(attrs={'class':'form-control', 'style': 'float:right'}))
    is_staff = forms.BooleanField(label="کارمند",required=False, widget=forms.CheckboxInput(attrs={'class':'form-control', 'style': 'float:right'}))
    first_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام")
    last_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام خانوادگی")
    code = forms.CharField(max_length=10, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="کد ملی", validators=[is_code])
    mobile = forms.CharField(max_length=11, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="موبایل", validators=[is_mobile])


class CustomerAddForm(forms.Form):
    KIND_REAL = 'real'
    KIND_LEGAL = 'legal'
    KIND_CHOICES = (
        (KIND_REAL, 'حقیقی'),
        (KIND_LEGAL, 'حقوقی')
    )
    kind = forms.CharField(widget=forms.Select(attrs={"class":"form-control"}, choices=KIND_CHOICES), label="نوع مشارکت کننده")
    sid = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="کد تفصیلی")
    is_active = forms.BooleanField(label="فعال", required=False, widget=forms.CheckboxInput(attrs={'class':'form-control', 'style': 'float:right', 'checked': True}))
    first_name = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام")
    last_name = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام خانوادگی")
    code = forms.CharField(max_length=10, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="کد ملی", validators=[is_code])
    brand = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام تجاری")
    ceoname = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام مدیرعامل")
    company = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام شرکت")
    ncode = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شناسه ملی", validators=[is_ncode])
    mobile = forms.CharField(max_length=11, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="موبایل", validators=[is_mobile])
    phone = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شماره ثابت", validators=[is_phone])
    fax = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شماره فکس", validators=[is_phone])
    email = forms.EmailField(max_length=250, required=False, widget=forms.EmailInput(attrs={'class':'form-control'}), label="ایمیل")
    postalcode = forms.CharField(max_length=10, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="کد پستی", validators=[is_postal])
    address = forms.CharField(max_length=250, required=False, widget=forms.Textarea(attrs={'class':'form-control', 'rows':3}), label="آدرس")


class CustomerChangeForm(forms.ModelForm):

    class Meta:
        model = CustomerModel
        fields = (
            'kind',
            'is_active',
            'sid',
            'user',
            'brand',
            'company',
            'ceoname',
            'ncode',
            'phone',
            'fax',
            'email',
            'postalcode',
            'address',
        )
        widgets = {
            'kind': forms.Select(attrs={'class':'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class':'form-control', 'style': 'float:right'}),
            'sid': forms.TextInput(attrs={'class':'form-control'}),
            'user': forms.TextInput(attrs={'class':'form-control', 'type':'hidden'}),
            'brand': forms.TextInput(attrs={'class':'form-control'}),
            'company': forms.TextInput(attrs={'class':'form-control'}),
            'ceoname': forms.TextInput(attrs={'class':'form-control'}),
            'ncode': forms.TextInput(attrs={'class':'form-control'}),
            'phone': forms.TextInput(attrs={'class':'form-control'}),
            'fax': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'postalcode': forms.TextInput(attrs={'class':'form-control'}),
            'address': forms.TextInput(attrs={'class':'form-control'}),
        }


class DocumentForm(forms.Form):
    file = forms.FileField(label='مدرک', validators=[validate_file_size])


class MessageForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows':2}), label="توضیحات", required=False)


# class MessageAddForm(forms.ModelForm):

#     class Meta:
#         model = MessagesModel
#         fields = (
#             'customer',
#             'text',
#         )
#         widgets = {
#             'customer': forms.Select(attrs={'class':'form-control', 'id':'id_user'}),
#             'text': forms.Textarea(attrs={'class':'form-control', 'rows':2}),
#         }


class RequestAcceptForm(forms.Form):
    area = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label="متراژ", validators=[is_positive])
    discount = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label="تخفیف", required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows':2}), label="توضیحات", required=False)


class ExhibitionForm(forms.ModelForm):

    class Meta:
        model = ExhibitionModel
        fields = (
            'is_active',
            'sid',
            'title',
            'price',
            'value_added',
            'min_area',
            'date',
        )
        widgets = {
            'is_active': forms.CheckboxInput(attrs={'class':'form-control', 'style': 'float:right', 'checked':True}),
            'sid': forms.TextInput(attrs={'class':'form-control'}),
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'price': forms.TextInput(attrs={'class':'form-control'}),
            'value_added': forms.TextInput(attrs={'class':'form-control'}),
            'min_area': forms.TextInput(attrs={'class':'form-control'}),
            'date': forms.TextInput(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(ExhibitionForm, self).__init__(*args, **kwargs)
        self.fields['date'] = JalaliDateField(label="تاریخ برگزاری", # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget() # optional, to use default datepicker
        )


class CustomerToExhibitionForm(forms.Form):
    KIND_PERCENT = 'check'
    KIND_CASH = 'cash'
    KIND_CHOICES = (
        (KIND_PERCENT, 'درصد'),
        (KIND_CASH, 'مبلغ'),
    )
    kind = forms.CharField(widget=forms.Select(attrs={"class":"form-control"}, choices=KIND_CHOICES), label="نوع تخفیف")
    exhibition = forms.ModelChoiceField(queryset=ExhibitionModel.objects.filter(is_active=True), label="نمایشگاه")
    booth_number = forms.CharField(max_length=50, required=False, label="شماره غرفه", widget=forms.TextInput(attrs={'class':'form-control'}), validators=[is_positive])
    discount = forms.CharField(max_length=50, required=True, label="مقدار تخفیف", widget=forms.TextInput(attrs={'class':'form-control'}), validators=[is_discount])
    area = forms.CharField(max_length=15, required=True, label="متراژ(مترمربع)", widget=forms.TextInput(attrs={'class':'form-control'}), validators=[is_positive])


class InvoiceAddForm(forms.Form):
    wallet = forms.ModelChoiceField(queryset=WalletModel.objects.filter(user__is_active=True), label="مشارکت کننده")
    booth_number = forms.CharField(label="شماره غرفه", max_length=4, required=False, validators=[is_positive], widget=forms.TextInput(attrs={'class':'form-control'}))

office/templates/office/customer-list.html
{% extends "base.html" %}
{% load jalali_tags %}
{% load humanize %}
{% load static %}

{% block title %}
لیست مشارکت کنندگان
{% endblock title %}

{% block content %}
<section id="page-content" class="background-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h2>لیست همه</h2>
                        <p>لطفاً از صحیح و بروز بودن اطلاعات مشارکت کنندگان اطمینان حاصل فرمایید!</p>
                    </div>
                </div>
            </div>
            {% if messages %}
            <div class="col-lg-12">
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div role="alert" class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> هشدار!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                    {% if message.tags == 'success' %}
                        <div role="alert" class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> تبریک!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-lg-12">
                                <div class="row">
                                    <div class="form-group col-lg-3">
                                        <input class="form-control" id="myInput" type="text" placeholder="جستجو...">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="table-responsive" style="height:500px;overflow:auto;">
                                    <table id="datatable" class="table table-bordered table-hover" style="width:100%;text-align:center">
                                        <thead class="thead-light">
                                            <tr>
                                                <th>کد</th>
                                                <th>کد معین</th>
                                                <th>نام تجاری</th>
                                                <th>موبایل</th>
                                                <th>کیف پول (ریال)</th>
                                                <th>تاریخ ایجاد</th>
                                                <th>عملیات</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for customer in customer %}
                                            <tr>
                                                <td>{{ customer.pk }}</td>
                                                <td>{% if customer.sid %}
                                                    {{ customer.sid }}
                                                    {% else %}
                                                    ---
                                                    {% endif %}
                                                </td>
                                                <td style="color:blueviolet" data-toggle="tooltip" data-placement="top" title="{% if customer.kind == 'legal' %}حقوقی{% else %}حقیقی{% endif %}">
                                                    <b>{{ customer.brand }} ( {% if customer.kind == "legal" %}{{ customer.company }}{% else %}{{ customer.user.first_name }} {{ customer.user.last_name }}{% endif %} )</b>
                                                </td>
                                                <td class="text-dark">
                                                    {% for i in mobile %}
                                                    {% if i.user.pk == customer.user.pk %}
                                                    {{ i.mobile }}
                                                    {% endif %}
                                                    {% endfor %}
                                                </td>
                                                <td>
                                                    {% for w in wallet %}
                                                    {% if w.user.pk == customer.user.pk %}
                                                    {{ w.cash|intcomma:False }}
                                                    {% endif %}
                                                    {% endfor %}
                                                </td>
                                                <td style="color:#003f5c">{{ customer.created_date|to_jalali:'%Y/%m/%d' }}</td>
                                                <td>
                                                    <a class="btn btn-sm" href="{% url 'office:customer-change' cid=customer.pk %}">مشاهده و ویرایش</a>
                                                    <a class="btn btn-sm" href="{% url 'office:document-list' cid=customer.pk %}">مدارک</a>
                                                    <a class="btn btn-success btn-sm" href="{% url 'office:customer-exhibition' id=customer.pk %}"> نمایشگاه ها</a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block script %}

<script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#datatable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>
{% endblock script %}

office/templates/office/documents-list.html
{% extends "base.html" %}
{% load jalali_tags %}
{% load static %}

{% block title %}
لیست مدارک مشارکت کنندگان
{% endblock title %}

{% block content %}
<section id="page-content" class="background-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body" data-bg-image="{% static 'images/docs.png' %}">
                        <h2>لیست مدارک</h2>
                        <p>لطفا مدارک بارگذاری شده را با دقت بررسی کرده و وضعیت آنهارا مشخص کنید.</p>
                        <p class="text-danger">توجه! درصورت استفاده از گزینه حذف، مدرک بارگذاری شده پاک شده و قابلیت بازگشت ندارد.</p>
                    </div>
                </div>
            </div>
            {% if messages %}
            <div class="col-lg-12">
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div role="alert" class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> هشدار!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                    {% if message.tags == 'success' %}
                        <div role="alert" class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> تبریک!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-lg-12">
                                <div class="row">
                                    <div class="form-group col-lg-2">
                                        <input class="form-control" id="myInput" type="text" placeholder="جستجو...">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="table-responsive" style="height:500px;overflow:auto;">
                                    <table id="datatable" class="table table-bordered table-hover" style="width:100%">
                                        <thead class="thead-light">
                                            <tr>
                                                <th>کد</th>
                                                <th>وضعیت</th>
                                                <th>کدملی</th>
                                                <th>نام و نشان</th>
                                                <th>مدارک</th>
                                                <th>تاریخ</th>
                                                <th>اقدامات</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for doc in doc %}
                                            <tr>
                                                <td>{{ doc.pk }}</td>
                                                <td>
                                                    {% if doc.state == "wait" %}
                                                    <span class="badge badge-pill badge-warning">در انتظار بررسی</span>
                                                    {% elif doc.state == "accept"  %}
                                                    <span class="badge badge-pill badge-success">قبول</span>
                                                    {% else %}
                                                    <span class="badge badge-pill badge-danger">رد شده</span>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    <a href="" style="color:blueviolet">{{ doc.user.username }}</a>
                                                </td>
                                                <td class="text-info">{{ doc.user.first_name }} {{ doc.user.last_name }}</td>
                                                <td><a href="{{ doc.file.url }}" target="_blank"></a></td>
                                                <td style="color:#003f5c">{{ doc.created_date|to_jalali:'%Y/%m/%d' }}</td>
                                                <td>
                                                    <a class="mr-2 text-success" href="{% url 'office:documents-accept' fid=doc.pk %}" data-toggle="tooltip" data-original-title="تایید"><i class="icon-check" style="font-size:large"></i></a>
                                                    <a class="mr-2 text-danger" href="{% url 'office:documents-deny' fid=doc.pk %}" data-toggle="tooltip" data-original-title="عدم تایید"><i class="icon-x-square" style="font-size:large"></i></a>
                                                    <a class="mr-2 text-info" href="{% url 'office:documents-del' fid=doc.pk %}" data-toggle="tooltip" data-original-title="حذف"><i class="icon-trash-2" style="font-size:large"></i></a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            {% comment %} <div class="col-lg-3 text-center">
                                <img src="{% static 'images/doclist.png' %}">
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block script %}

<script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#datatable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>
{% endblock script %}

office/templates/office/none.html
{% extends "base.html" %}
{% load static %}
{% block title %}

{% endblock title %}
{% block content %}
<section class="m-t-80 p-b-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div data-bg-image="{% static 'images/error.png' %}" style="height:400px">

                </div>
            </div>
            <div class="col-lg-6">
                <div class="text-left">
                    {% if title %}
                    <h1 class="text-medium">{{ title }}</h1>
                    {% endif %}
                    {% if content %}
                    <p class="lead">{{ content }}</p>
                    {% endif %}
                    <div class="seperator m-t-20 m-b-20"></div>
                    <div class="search-form">
                        <p>لطفا دوباره جستجو کنید</p>
                        <form action="search-results-page.html" method="get" class="form-inline">
                            <div class="input-group input-group-lg">
                                <input type="text" aria-required="true" name="q" class="form-control widget-search-form" placeholder="جستجو کنید ...">
                                <div class="input-group-append">
                                    <span class="input-group-btn">
                                        <button type="submit" id="widget-widget-search-form-button" class="btn"><i class="fa fa-search"></i></button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}