client/urls.py
from django.urls import path
from .views import *

app_name = "client"

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/add/", ProfileAddView.as_view(), name="profile-add"),
    path("profile/edit/<int:pid>/", ProfileEditView.as_view(), name="profile-edit"),
    path("exhibition/", ExhibitionView.as_view(), name="exhibition"),
    path("document/add/<int:cid>/", DocumentAddView.as_view(), name="document-add"),
    path("request//add/", RequestAddView.as_view(), name="request-add"),
    path("request/document/add/<int:rid>/", RequestDocumentAddView.as_view(), name="request-document-add"),
    path("invoice/", InvoiceView.as_view(), name="invoice"),
    path("invoice/details/<int:iid>/", InvoiceDetailsView.as_view(), name="invoice-details"),
    path("invoice/done/<int:iid>/", InvoiceDoneView.as_view(), name="invoice-done"),
    path("payment/create/<int:iid>/<str:pay>/", PaymentCreateView.as_view(), name="payment-create"),
    path("payment/<int:iid>/done/", PaymentDoneView.as_view(), name="payment-done"),
    ]

crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('client/', include('client.urls', namespace='client')),
    path('main/', include('office.urls', namespace='office')),
    path('', include('portal.urls', namespace='portal')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

admin.site.site_header = 'پورتال شرکت نمایشگاه بین‌المللی ارومیه'

client/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from random import randint

# Create your models here.

def documents_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = f"{randint(100000, 999999)}.{ext}"
    return os.path.join(f"{instance.customer.pk}/", filename)
    # "{0}/{1}".format(instance.user.id, filename)

def request_documents_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = f"{randint(100000, 999999)}.{ext}"
    return os.path.join(f"{instance.request.customer.pk}/", filename)
    # "{0}/{1}".format(instance.user.id, filename)


class BaseModel(models.Model):
    user_modified = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_modified',
        null=True,
        blank=True,
        verbose_name='کاربر ویرایش'
        )
    user_created = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_created',
        null=True,
        blank=True,
        verbose_name='کاربر ایجاد'
        )
    created_date = models.DateTimeField(verbose_name='تاریخ ایجاد', auto_now_add=True)
    modified_date = models.DateTimeField(verbose_name='تاریخ تغییرات', auto_now=True)

    class Meta:
        abstract = True


class CustomerModel(BaseModel):
    KIND_REAL = 'real'
    KIND_LEGAL = 'legal'
    KIND_CHOICES = (
        (KIND_REAL, 'حقیقی'),
        (KIND_LEGAL, 'حقوقی')
    )
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    sid = models.CharField(verbose_name='کد تفصیلی', max_length=50, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    kind = models.CharField(verbose_name='نوع مشارکت کننده', max_length=50, choices=KIND_CHOICES, default=KIND_REAL)
    brand = models.CharField(verbose_name='نام تجاری', max_length=100)
    company = models.CharField(verbose_name='نام شرکت', max_length=100, null=True, blank=True)
    ceoname = models.CharField(verbose_name='نام مدیرعامل', max_length=100, null=True, blank=True)
    ncode = models.CharField(verbose_name='شناسه ملی', max_length=11, null=True, blank=True)
    phone = models.CharField(verbose_name='تلفن', max_length=11, null=True, blank=True)
    fax = models.CharField(verbose_name='فکس', max_length=11, null=True, blank=True)
    email = models.EmailField(verbose_name='ایمیل', null=True, blank=True)
    postalcode = models.CharField(verbose_name='کد پستی', max_length=10, null=True, blank=True)
    address = models.TextField(verbose_name='آدرس', null=True, blank=True)

    def __str__(self):
        if self.kind == self.KIND_REAL:
            if self.user:
                return f"{self.brand}({self.user.first_name} {self.user.last_name})"
            else:
                return f"{self.brand}"
        else:
            if self.user:
                return f"{self.brand}-{self.company}({self.user.first_name} {self.user.last_name})"
            else:
                return f"{self.brand}-{self.company}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["brand", "user"], name='branduser'),
            models.UniqueConstraint(fields=["sid"], name='specid')
    ]
        verbose_name = 'مشارکت کننده'
        verbose_name_plural = 'مشارکت کنندگان'


class DocumentsModel(BaseModel):
    STATE_WAIT = 'wait'
    STATE_ACCEPT = 'accept'
    STATE_DENY = 'deny'
    STATE_CHOICES = (
        (STATE_WAIT, 'در انتظار بررسی'),
        (STATE_ACCEPT, 'قبول شده'),
        (STATE_DENY, 'رد شده')
    )
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_WAIT)
    customer = models.ForeignKey(CustomerModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    file = models.FileField(verbose_name='مدرک', upload_to=documents_directory_path)
    description = models.TextField(verbose_name="توضیحات", null=True, blank=True)

    def __str__(self):
        if self.customer is not None:
            return f"{self.customer.brand} - {self.file.name}"
        return self.file.name
    
    class Meta:
        verbose_name = 'مدرک'
        verbose_name_plural = 'مدارک'


class ExhibitionModel(BaseModel):
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    sid = models.CharField(verbose_name='کد معین', max_length=50, null=True, blank=True)
    title = models.CharField(verbose_name='عنوان نمایشگاه', max_length=200)
    price = models.CharField(verbose_name='قیمت', max_length=20)
    value_added = models.CharField(verbose_name='ارزش افزوده', max_length=10)
    min_area = models.CharField(verbose_name='حداقل متراژ(مترمربع)', max_length=100)
    date = models.DateField(verbose_name='تاریخ برگزاری', null=True, blank=True)

    def __str__(self):
        return f"{self.title} - {self.date.year}"
    
    class Meta:
        verbose_name = 'نمایشگاه'
        verbose_name_plural = 'نمایشگاه‌ها'

class WalletModel(BaseModel):
    user = models.OneToOneField(User, on_delete=models.PROTECT, verbose_name="کاربر")
    cash = models.CharField(verbose_name="موجودی(ریال)", max_length=15, default="0")

    def __str__(self):
        return f"{self.user.username} ({self.user.first_name} {self.user.last_name})"
    
    class Meta:
        verbose_name = "کیف پول"
        verbose_name_plural = "کیف‌های پول"


class InvoiceModel(BaseModel):
    STATE_PAID = "paid"
    STATE_UNPAID = "unpaid"
    STATE_CHOICES = (
        (STATE_PAID, "پرداخت شده"),
        (STATE_UNPAID, "پرداخت نشده")
    )
    is_active = models.BooleanField(verbose_name="فعال", default=True)
    state = models.CharField(verbose_name="وضعیت", max_length=50, choices=STATE_CHOICES, default=STATE_UNPAID)
    wallet = models.ForeignKey(WalletModel, on_delete=models.SET_NULL, verbose_name="کیف پول", null=True, blank=True)
    customer = models.ForeignKey(CustomerModel, on_delete=models.SET_NULL, verbose_name="مشارکت کننده", null=True, blank=True)
    exhibition = models.ForeignKey(ExhibitionModel, on_delete=models.SET_NULL, verbose_name="نمایشگاه", null=True, blank=True)
    booth_number = models.CharField(verbose_name="شماره غرفه", max_length=100, null=True, blank=True)
    price = models.CharField(verbose_name="مبلغ", max_length=20, default="0")
    area = models.CharField(verbose_name="متراژ(مترمربع)", max_length=9, default="0")
    value_added = models.CharField(verbose_name="ارزش افزوده(درصد)", max_length=10, default="0")
    discount = models.CharField(verbose_name="تخفیف(درصد)", max_length=3, default="0")
    amount = models.CharField(verbose_name="مبلغ نهایی", max_length=20, default="0")

    def __str__(self):
        if self.customer:
            return f"ش: {self.pk}-{self.customer.brand} ({self.exhibition.title})"
        return f"ش: {self.pk}-({self.exhibition.title})"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["customer", "exhibition", "booth_number"], name='customer_exhibition_booth')
    ]
        verbose_name = "فاکتور"
        verbose_name_plural = "فاکتورها"

        
class BankModel(BaseModel):
    KIND_CURRENT = 'current'
    KIND_SHORT = 'short'
    KIND_LOAN = 'loan'
    KIND_CHOICES = (
        (KIND_CURRENT, "حساب جاری"),
        (KIND_SHORT, "حساب کوتاه مدت"),
        (KIND_LOAN, "حساب قرض‌الحسنه")
    )
    name = models.CharField(verbose_name="نام", max_length=100)
    account_number = models.CharField(verbose_name="شماره حساب", max_length=100)
    kind = models.CharField(verbose_name="نوع حساب", max_length=100, choices=KIND_CHOICES, default=KIND_CURRENT)

    def __str__(self):
        return f"{self.name}-{self.account_number}"
    
    class Meta:
        verbose_name = "حساب بانک"
        verbose_name_plural = "حساب بانک‌ها"


class PaymentModel(BaseModel):
    STATE_CHECK = 'check'
    STATE_CASH = 'cash'
    STATE_POS = 'pos'
    STATE_IPG = 'ipg'
    STATE_CHOICES = (
        (STATE_CHECK, 'چک بانکی'),
        (STATE_CASH, 'نقدی'),
        (STATE_POS, 'پوز بانکی'),
        (STATE_IPG, 'درگاه اینترنتی'),
    )
    state = models.CharField(verbose_name="وضعیت", max_length=50, choices=STATE_CHOICES, default=STATE_POS)
    wallet = models.ForeignKey(WalletModel, on_delete=models.PROTECT, verbose_name="کیف پول")
    invoice = models.ForeignKey(InvoiceModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="فاکتور")
    bank = models.ForeignKey(BankModel, on_delete=models.SET_NULL, verbose_name="حساب بانکی", null=True, blank=True)
    amount = models.IntegerField(verbose_name="مبلغ", default=1000)
    cardnumber = models.CharField(verbose_name="شماره کارت/چک", max_length=32, null=True, blank=True)
    issuerbank = models.CharField(verbose_name="بانک صادرکننده", max_length=150, null=True, blank=True)
    name = models.CharField(verbose_name="مشخصات صاحب چک", max_length=150, null=True, blank=True)
    rrn = models.CharField(verbose_name="شماره سند بانکی", max_length=150, null=True, blank=True)
    tracenumber = models.CharField(verbose_name="شماره پیگیری", max_length=150, null=True, blank=True)
    digitalreceipt = models.CharField(verbose_name="رسید دیجیتال", max_length=150, null=True, blank=True)
    respcode = models.IntegerField(verbose_name="کد نتیجه تراکنش", default=0, null=True, blank=True)
    respmsg = models.CharField(verbose_name="متن نتیجه تراکنش", max_length=150, null=True, blank=True)
    payload = models.CharField(verbose_name="توضیحات", max_length=150, null=True, blank=True)
    datepaid = models.CharField(verbose_name="تاریخ و زمان تراکنش", max_length=50, null=True, blank=True)

    def __str__(self):
        if self.state == self.STATE_POS:
            return f"{self.wallet.user.username} - شماره پیگیری: {self.tracenumber}"
        return f"{self.state}-{self.invoice.customer.brand} - مبلغ: {self.amount}"
    
    class Meta:

client/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget
from crm.settings import Terminal_id
    
def persian_digits_to_english(s:str):
    persian_digits = "۰۱۲۳۴۵۶۷۸۹"
    english_digits = "0123456789"
    translate_table = str.maketrans(persian_digits, english_digits)
    return s.translate(translate_table)

def is_code(value):
    if len(value) != 10 or not str(persian_digits_to_english(value)).isnumeric():
        raise ValidationError('کد ملی صحیح نمی‌باشد!')
    
def is_mobile(value):
    if not str(persian_digits_to_english(value)).isnumeric() or len(value) !=11 or str(persian_digits_to_english(value))[0] != '0':
        raise ValidationError('شماره موبایل صحیح نمی‌باشد!')
    
def is_phone(value):
    if not str(persian_digits_to_english(value)).isnumeric() or len(value) !=11 or str(persian_digits_to_english(value))[0] != '0':
        raise ValidationError('شماره تلفن صحیح نمی‌باشد!')
    
def is_ncode(value):
    if len(value) != 11 or not str(persian_digits_to_english(value)).isnumeric():
        raise ValidationError("شناسه ملی صحیح نمی‌باشد.")
    
def is_postal(value):
    if len(value) != 10 or not str(persian_digits_to_english(value)).isnumeric():
        raise ValidationError('کد پستی صحیح نمی‌باشد!')
    
def is_positive(value):
    if not str(persian_digits_to_english(value)).isnumeric():
        raise ValidationError('لطفاً فقط عدد وارد کنید!')
    if str(persian_digits_to_english(value)).isnumeric():
        if int(value) < 1:
            raise ValidationError('عدد باید بزرگتر از صفر باشد!')
        
def is_discount(value):
    if not str(persian_digits_to_english(value)).isnumeric():
        raise ValidationError('لطفاً فقط عدد وارد کنید!')
    if str(persian_digits_to_english(value)).isnumeric():
        if int(value) < 0:
            raise ValidationError('کمترین مقدار می‌تواند عدد صفر باشد!')
        

class PaymentCreateForm(forms.Form):
    TerminalID = forms.CharField(widget=forms.TextInput(attrs={'name':'TerminalID'}))
    token = forms.CharField(widget=forms.TextInput(attrs={'name':'token'}))
        

class ProfileAddForm(forms.Form):
    KIND_REAL = 'real'
    KIND_LEGAL = 'legal'
    KIND_CHOICES = (
        (KIND_REAL, 'حقیقی'),
        (KIND_LEGAL, 'حقوقی')
    )
    kind = forms.CharField(widget=forms.Select(attrs={"class":"form-control"}, choices=KIND_CHOICES), label="نوع مشارکت کننده")
    first_name = forms.CharField(max_length=250, required=False, disabled=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام")
    last_name = forms.CharField(max_length=250, required=False, disabled=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام خانوادگی")
    code = forms.CharField(max_length=10, required=False, disabled=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="کد ملی", validators=[is_code])
    brand = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام تجاری")
    ceoname = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام مدیرعامل")
    company = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="نام شرکت")
    ncode = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شناسه ملی", validators=[is_ncode])
    mobile = forms.CharField(max_length=11, required=False, disabled=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="موبایل", validators=[is_mobile])
    phone = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شماره ثابت", validators=[is_phone])
    fax = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شماره فکس", validators=[is_phone])
    email = forms.EmailField(max_length=250, required=False, widget=forms.EmailInput(attrs={'class':'form-control'}), label="ایمیل")
    postalcode = forms.CharField(max_length=10, required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label="کد پستی", validators=[is_postal])
    address = forms.CharField(max_length=250, required=True, widget=forms.Textarea(attrs={'class':'form-control', 'rows':3}), label="آدرس")


class DocumentAddForm(forms.Form):
    file = forms.FileField(label="مدارک")


class RequestAddForm(forms.Form):
    exhibition = forms.CharField(label="عنوان نمایشگاه", required=True, widget=forms.Select())
    customer = forms.CharField(label="حساب کاربری", required=True, widget=forms.Select())
    rules = forms.BooleanField(label="قوانین و مقررات", required=True)
    description = forms.CharField(label="توضیحات", required=True, widget=forms.Textarea(attrs={"class":"form-control", "rows":"5"}))

client/templates/client/exhibition.html
{% extends "base-c.html" %}

{% block title %}
نمایشگاه‌ها | شرکت نمایشگاه بین‌المللی ارومیه
{% endblock title %}

{% block content %}
<section id="page-title">
    <div class="container">
        <div class="breadcrumb">
        </div>
        <div class="page-title">
            <h1>لیست درخواست‌ها</h1>
        </div>
    </div>
</section>
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 text-center">
            <div class="card">
                <div class="card-body">
                    <div class="mt-4">
                        <ul class="list-icon list-icon-plus list-icon-colored">
                            <li><a href="{% url 'client:request-add' %}">درخواست جدید</a></li>
                        </ul>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            {% for req in req %}
            <div class="modal fade" id="modal-{{ req.pk }}" tabindex="-1" role="modal" aria-labelledby="modal-label" aria-hidden="true"
                style="display: none;">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="modal-label">مدرک جدید</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        </div>
                        <form method="post" action="{% url 'client:request-document-add' rid=req.pk %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <input id="id_file" name="file" type="file" required>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-b" value="بارگذاری">
                        </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4>درخواست</h4>
                </div>
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-12">
                            {% if req.state == "accept" %}
                            <input class="form-control" type="text" value="درخواست تایید شده">
                            {% elif req.state == "deny" %}
                            <input class="form-control" type="text" value="درخواست تایید نشده">
                            {% else %}
                            <input class="form-control" type="text" value="در انتظار بررسی">
                            {% endif %}
                        </div>
                        <div class="form-group col-6">
                            <input class="form-control" type="text" value="{{ req.exhibition.title }}">
                        </div>
                        <div class="form-group col-6">
                            <input class="form-control" type="text" value="{{ req.customer.brand }}">
                        </div>
                        <div class="form-group col-12">
                            <textarea class="form-control" rows="2">{{ req.description }}</textarea>
                        </div>
                        <div class="form-group col-12">
                            <label>پیام مدیر</label>
                            <textarea class="form-control" rows="2">{% if req.message %}{{ req.message }}{% endif %}</textarea>
                        </div>
                        {% for doc in req.requestdocumentsmodel_set.all %}
                        <div class="form-group col-4">
                            <a class="" href="{{ doc.file.url }}">{{ doc.file }}<a>
                        </div>
                        {% endfor %}
                        <div class="form-group col-12">
                            <a class="btn btn-xs btn-success" data-target="#modal-{{ req.pk }}" data-toggle="modal" href="#">مدرک جدید</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

client/templates/client/index.html
{% extends "base-c.html" %}

{% block title %}
حساب من | شرکت نمایشگاه بین‌المللی ارومیه
{% endblock title %}

{% block content %}
<section id="page-title">
    <div class="container">
        <div class="page-title">
            <h1>صفحه اصلی حساب کاربری</h1>
        </div>
    </div>
</section>
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-lg-4 text-center">
            <div class="icon-box effect medium center">
                <div class="icon"> <a href="{% url 'client:profile' %}"><i class="fa fa-user-edit"></i></a> </div>
                <a href="{% url 'client:profile' %}"><h3>اطلاعات حساب</h3></a>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <div class="icon-box effect medium center">
                <div class="icon"> <a href="{% url 'client:exhibition' %}"><i class="fa fa-desktop"></i></a> </div>
                <a href="{% url 'client:exhibition' %}"><h3>نمایشگاه‌</h3></a>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <div class="icon-box effect medium center">
                <div class="icon"> <a href="{% url 'client:invoice' %}"><i class="fa fa-shopping-bag"></i></a> </div>
                <a href="{% url 'client:invoice' %}"><h3>صورتحساب</h3></a>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <div class="icon-box effect medium center">
                <div class="icon"> <a href="#"><i class="fa fa-credit-card"></i></a> </div>
                <a href="#"><h3>مالی</h3></a>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <div class="icon-box effect medium center">
                <div class="icon"> <a href="#"><i class="fa fa-headphones"></i></a> </div>
                <a href="#"><h3>تیکت پشتیبانی</h3></a>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <div class="icon-box effect medium center">
                <div class="icon"> <a href="#"><i class="fa fa-exclamation-circle"></i></a> </div>
                <a href="#"><h3>قوانین و مقررات</h3></a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

client/templates/client/invoice.html
{% extends "base-c.html" %}

{% block title %}
فاکتورها | شرکت نمایشگاه بین‌المللی ارومیه
{% endblock title %}

{% block content %}
<section id="page-title">
    <div class="container">
        <div class="breadcrumb">
        </div>
        <div class="page-title">
            <h1>فاکتورها</h1>
        </div>
    </div>
</section>
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                {% for invoice in invoices %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <h3>
                        {% if invoice.state == "paid" %}
                        <span class="badge badge-success">
                        <i class="icon-check"></i>
                        </span>
                        {% else %}
                        <span class="badge badge-danger">
                        <i class="icon-x"></i>
                        </span>
                        {% endif %}
                    </h3>
                    <p class="h3">{{ invoice.exhibition.title }} - {{ invoice.customer.brand }}<br>
                        <span class="text-muted"><small>شماره فاکتور: {{ invoice.pk }}</small></span>
                    </p>

                    <a href="{% url 'client:invoice-details' iid=invoice.pk %}" class="h5 text-primary">جزئیات<i class="icon-chevron-left"> </i></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

client/templates/client/payment-create.html
{% extends "base-c.html" %}

{% block content %}
<form id="myForm" method="post" action="https://sepehr.shaparak.ir:8080/Pay">
    {% csrf_token %}
    {{ form.TermialID }}
    {{ form.token }}
    <input type="submit" value=" پرداخت" class="submit" />
</form>
{% endblock content %}

client/templates/client/payment-done.html
{% extends "base-c.html" %}

{% block title %}
نتیجه تراکنش | شرکت نمایشگاه بین‌المللی ارومیه
{% endblock title %}

{% block content %}
        <section class="m-t-80 p-b-150">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="page-error-404 text-center">{{ code }}</div>
                    </div>
                    <div class="col-lg-6">
                        <div class="text-left">
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                    <div role="alert" class="alert alert-danger alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                                        <strong><i class="fa fa-exclamation-circle"></i> هشدار!</strong> 
                                        {{ message}}
                                    </div>
                                {% endif %}
                                {% if message.tags == 'success' %}
                                    <div role="alert" class="alert alert-success alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                                        <strong><i class="fa fa-exclamation-circle"></i> تبریک!</strong> 
                                        {{ message}}
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div class="seperator m-t-20 m-b-20"></div><a href="{% url 'client:index' %}"
                                class="btn" type="button">بازگشت به صفحه اصلی</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock content %}

client/templates/client/permission.html
{% extends "base-c.html" %}

{% block title %}

{% endblock title %}

{% block content %}
<section class="m-t-80 p-b-150">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-left">
                            <h1 class="text-medium">خطای دسترسی!!</h1>
                            <p class="lead">متأسفیم، شما مجوز نمایش این صفحه را ندارید.</p>
                            <div class="seperator m-t-20 m-b-20"></div><button onclick="window.location.reload()" class="btn" type="button">بارگذاری مجدد صفحه</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock content %}