accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('verify/<str:code>/', MobileVerifyView.as_view(), name='verify'),
    path('change/mobile/<str:code>/', ChangeMobileView.as_view(), name='change-mobile'),
    path('re-token/<str:code>/', ReTokenView.as_view(), name='re-token'),
    ]

client/urls.py
from django.urls import path
from .views import *

app_name = "client"

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/add/", ProfileAddView.as_view(), name="profile-add"),
    path("profile/edit/<int:pid>/", ProfileEditView.as_view(), name="profile-edit"),
    path("exhibition/", ExhibitionView.as_view(), name="exhibition"),
    path("document/add/<int:cid>/", DocumentAddView.as_view(), name="document-add"),
    path("request//add/", RequestAddView.as_view(), name="request-add"),
    path("request/document/add/<int:rid>/", RequestDocumentAddView.as_view(), name="request-document-add"),
    path("invoice/", InvoiceView.as_view(), name="invoice"),
    path("invoice/details/<int:iid>/", InvoiceDetailsView.as_view(), name="invoice-details"),
    path("invoice/done/<int:iid>/", InvoiceDoneView.as_view(), name="invoice-done"),
    path("payment/create/<int:iid>/<str:pay>/", PaymentCreateView.as_view(), name="payment-create"),
    path("payment/<int:iid>/done/", PaymentDoneView.as_view(), name="payment-done"),
    ]

crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('client/', include('client.urls', namespace='client')),
    path('main/', include('office.urls', namespace='office')),
    path('', include('portal.urls', namespace='portal')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

admin.site.site_header = 'پورتال شرکت نمایشگاه بین‌المللی ارومیه'

office/urls.py
from django.urls import path
from .views import *

app_name = "office"

urlpatterns = [
    path('', Test.as_view(), name='test'),
    path('home/', HomeView.as_view(), name='home'),
    path('user/add/', UserAddView.as_view(), name='user-add'),
    path('customer/list/', CustomerListView.as_view(), name='customer-list'),
    path('deactive/customer/list/', DeactiveCustomerListView.as_view(), name='deactive-customer-list'),
    path('profile/accept/<int:pid>/', ProfileAcceptView.as_view(), name='profile-accept'),
    path('profile/deny/<int:pid>/', ProfileDenyView.as_view(), name='profile-deny'),
    path('customer/add/', CustomerAddView.as_view(), name='customer-add'),
    path('customer/change/<int:cid>/', CustomerChangeView.as_view(), name='customer-change'),
    path('customer/exhibition/<int:id>/', CustomerExhibitionView.as_view(), name='customer-exhibition'),
    path('customer/exhibition/edit/<int:id>/', CustomerExhibitionEditView.as_view(), name='customer-exhibition-edit'),
    path('request/list/', RequestListView.as_view(), name='request-list'),
    path('request/state/<int:rid>/', RequestStateView.as_view(), name='request-state'),
    path('invoice/list/', InvoiceListView.as_view(), name='invoice-list'),
    path('invoice/remove/<int:iid>/', InvoiceRemoveView.as_view(), name='invoice-remove'),
    path('invoice/edit/<int:iid>/', InvoiceEditView.as_view(), name='invoice-edit'),
    path('document/list/<int:cid>/', DocumentListView.as_view(), name='document-list'),
    path('document/add/<int:id>/', DocumentsAddView.as_view(), name='documents-add'),
    path('document/del/<int:fid>/', DocumentsDelView.as_view(), name='documents-del'),
    path('document/accept/<int:fid>/', DocumentsAcceptView.as_view(), name='documents-accept'),
    path('document/deny/<int:fid>/', DocumentsDenyView.as_view(), name='documents-deny'),
    # path('message/list/', MessagesListView.as_view(), name='message-list'),
    # path('message/add/', MessageAddView.as_view(), name='message-add'),
    # path('message/change/<int:mid>/', MessageChangeView.as_view(), name='message-change'),
    path('exhibition/add/', ExhibitionAddView.as_view(), name='exhibition-add'),
    path('exhibition/list/', ExhibitionListView.as_view(), name='exhibition-list'),
    path('exhibition/details/<int:eid>/', ExhibitionDetailsView.as_view(), name='exhibition-details'),
    path('exhibition/details/<int:eid>/<int:iid>/', ExhibitionDetailsEditView.as_view(), name='exhibition-details-edit'),
    path('exhibition/status/<int:id>/', ExhibitionStatusView.as_view(), name='exhibition-status'),
    path('payment/list/', PaymentListView.as_view(), name='payment-list'),
    path('payment/add/<int:iid>/', PaymentAddView.as_view(), name='payment-add'),
    path('payment/remove/<int:pid>/', PaymentRemoveView.as_view(), name='payment-remove'),
    path('payment/edit/<int:iid>/<int:pid>/', PaymentEditView.as_view(), name='payment-edit'),
    path('payment/checkout/<int:iid>/', CheckoutView.as_view(), name='checkout'),
    path('payment/checkout/invoice/<int:iid>/', InvoicePrintView.as_view(), name='invoice-print'),
    path('payment/exit/permit/<int:iid>/', ExitPermitView.as_view(), name='exit-permit'),
    # path('payment/deposit/add/', DepositAddView.as_view(), name='deposit-add'),
    # path('payment/deposit/state/<int:did>/', DepositStateAddView.as_view(), name='deposit-state-add'),
    # path('payment/deposit/list/', DepositListView.as_view(), name='deposit-list'),
    ]

templates/base-c.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="example" />
    <meta name="description" content="سامانه مشتریان شرکت نمایشگاه بین‌المللی ارومیه">
    <link rel="icon" type="image/png" href="{% static 'images/fav-logo.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}{% endblock title %}</title>

    <link href="{% static 'css/plugins.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/rtl.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script>
        window.onload = function() {
            document.getElementById("myForm").submit();
        };
    </script>


</head>
<body>
</head>

<body data-icon="17">

    <div class="body-inner">
        <header id="header" data-fullwidth="true" class="header-always-fixed">
            <div class="header-inner">
                <div class="container">
                    <div id="logo">
                        <a href="https://www.urmiafair.com">
                            <span class="logo-default">UIF</span>
                            <span class="logo-dark">UIF</span>
                        </a>
                    </div>
                        
                    <div class="header-extras">
                        <ul>
                            <li>
                                <div class="p-dropdown">
                                    <a href="#"><i class="icon-user"></i></a>
                                    <ul class="p-dropdown-content">
                                        <ul class="text-center">
                                            {% comment %} <li><a href="#"><i class="icon-mail"></i>پیام ها</a></li> {% endcomment %}
                                            <li><a href="#"><i class="icon-settings"></i>تنظیمات</a></li>
                                            <li>
                                                <a href="{% url 'accounts:signout' %}"><i class="icon-log-out"></i>خروج</a>
                                            </li>
                                        </ul>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a href="#"> <i class="icon-bell"></i><sup style="top:-0.6em; font-size:1.2em"><b class="text-danger"></b></sup></a>
                            </li>
                        </ul>
                    </div>
                        
                        
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>

                    <div id="mainMenu" class="menu-center">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="{% url 'client:index' %}">خانه</a></li>
                                    <li><a href="{% url 'client:profile' %}">اطلاعات حساب‌</a></li>
                                    <li><a href="{% url 'client:exhibition' %}">نمایشگاه</a></li>
                                    <li><a href="{% url 'client:invoice' %}">صورتحساب</a></li>
                                    <li><a href="#">مالی</a></li>
                                    <li><a href="#">تیکت‌ها</a></li>
                                    <li><a href="#">قوانین و مقررات</a></li>
                                    {% comment %} <li class="dropdown"><a href="#">درخواست‌ها</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'crm:request-list' %}">لیست همه</a></li>
                                            <li><a href="{% url 'crm:request-add' %}">جدید</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'crm:messages' %}">پیام‌ها</a>  </li>
                                    <li><a href="{% url 'crm:help' %}">راهنما</a></li> {% endcomment %}
                                </ul>
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
        </header>
        {% block content %}{% endblock content %}
        <footer id="footer">
            <div class="footer-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 text-left">
                            <div class="icon-box effect medium center">
                                <div class="icon">
                                    <a href="#"><i class="fa fa-clock"></i></a>
                                </div>
                                <h3>روزهای کاری</h3>
                                <p><strong>شنبه تا پنج‌شنبه</strong>
                                    <br>8:30 الی 14:30</p>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="icon-box effect medium center">
                                <div class="icon">
                                    <a href="#"><i class="fas fa-map-marker-alt"></i></a>
                                </div>
                                <h3>موقعیت مکانی</h3>
                                <p>
                                     پارک جنگلی<br>
                                    محل دائمی نمایشگاه‌‌ها
                                </p>
                            </div>
                        </div>
                        <div class="col-md-4 text-right">
                            <div class="icon-box effect medium center">
                                <div class="icon">
                                    <a href="#"><i class="fa fa-phone"></i></a>
                                </div>
                                <h3>شماره تماس پشتیبانی</h3>
                                <p>04433369905
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6">

                            <div class="social-icons social-icons-colored float-left">
                                <img src="{% static 'images/uif-f.png' %}" alt="logo" style="max-width:70px">
                            </div>

                        </div>
                        <div class="col-lg-6">
                            <div class="copyright-text text-center">© تمام حقوق این سامانه متعلق به شرکت نمایشگاه بین‌المللی ارومیه می‌باشد.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>

    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
    
  <!-- Include jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Include Select2 JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
   
{% block script %}{% endblock script %}
</body>

</html>

templates/base-p.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="example" />
    <meta name="description" content="سامانه مشتریان شرکت نمایشگاه بین‌المللی ارومیه">
    <link rel="icon" type="image/png" href="{% static 'images/fav-logo.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}{% endblock title %}</title>

    <link href="{% static 'css/plugins.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/rtl.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</head>
<body>
</head>

<body data-icon="17">

    <div class="body-inner">
        <header id="header" data-fullwidth="true" class="header-always-fixed">
            <div class="header-inner">
                <div class="container">
                    <div id="logo">
                        <a href="https://www.urmiafair.com">
                            <span class="logo-default">UIF</span>
                            <span class="logo-dark">UIF</span>
                        </a>
                    </div>
                        
                    <div class="header-extras">
                        <ul>
                            <li>
                                <div class="p-dropdown">
                                    <a href="#"><i class="icon-user"></i></a>
                                    <ul class="p-dropdown-content">
                                        <ul class="text-center">
                                            {% comment %} <li><a href="#"><i class="icon-mail"></i>پیام ها</a></li> {% endcomment %}
                                            <li><a href="#"><i class="icon-settings"></i>تنظیمات</a></li>
                                            <li>
                                                <a href="{% url 'accounts:signout' %}"><i class="icon-log-out"></i>خروج</a>
                                            </li>
                                        </ul>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a href="#"> <i class="icon-bell"></i><sup style="top:-0.6em; font-size:1.2em"><b class="text-danger"></b></sup></a>
                            </li>
                        </ul>
                    </div>
                        
                        
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>

                    <div id="mainMenu" class="menu-center">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="{% url 'portal:index' %}">خانه</a></li>
                                    <li><a href="https://www.urmiafair.com">وب سایت</a></li>
                                    <li><a href="https://www.urmiafair.com/events/">تقویم نمایشگاه‌ها</a></li>
                                    <li><a href="https://www.urmiafair.com/news/">اخبار</a></li>
                                    {% comment %} <li class="dropdown"><a href="#">درخواست‌ها</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'crm:request-list' %}">لیست همه</a></li>
                                            <li><a href="{% url 'crm:request-add' %}">جدید</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'crm:messages' %}">پیام‌ها</a>  </li>
                                    <li><a href="{% url 'crm:help' %}">راهنما</a></li> {% endcomment %}
                                </ul>
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
        </header>
        {% block content %}{% endblock content %}
        <footer id="footer">
            <div class="footer-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <div class="icon-box effect medium center">
                                <div class="icon">
                                    <a href="#"><i class="fa fa-clock"></i></a>
                                </div>
                                <h3>روزهای کاری</h3>
                                <p><strong>شنبه تا پنج‌شنبه</strong>
                                    <br>8:30 الی 14:30</p>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="icon-box effect medium center">
                                <div class="icon">
                                    <a href="#"><i class="fas fa-map-marker-alt"></i></a>
                                </div>
                                <h3>موقعیت مکانی</h3>
                                <p>
                                     
                                     پارک جنگلی
                                    <br>محل دائمی نمایشگاه‌‌ها
                                    <br>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="icon-box effect medium center">
                                <div class="icon">
                                    <a href="#"><i class="fa fa-phone"></i></a>
                                </div>
                                <h3>شماره تماس پشتیبانی</h3>
                                <p>04433369905
                                </p>
                            </div>
                        </div>
                        <div class="col-md-12 text-center">
                            <a referrerpolicy="origin" target="_blank" href="https://trustseal.enamad.ir/?id=346702&amp;Code=TScSUG8zPCv3ITHmLIw4">
                                <img referrerpolicy="origin" src="https://Trustseal.eNamad.ir/logo.aspx?id=346702&amp;Code=TScSUG8zPCv3ITHmLIw4" alt="" style="cursor:pointer;width:100px" id="TScSUG8zPCv3ITHmLIw4">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6">

                            <div class="social-icons social-icons-colored float-left">
                                <img src="{% static 'images/uif-f.png' %}" alt="logo" style="max-width:70px">
                            </div>

                        </div>
                        <div class="col-lg-6">
                            <div class="copyright-text text-center">© تمام حقوق این سامانه متعلق به شرکت نمایشگاه بین‌المللی ارومیه می‌باشد.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>

    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
    
  <!-- Include jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Include Select2 JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
   
{% block script %}{% endblock script %}
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="example" />
    <meta name="description" content="سامانه مشتریان شرکت نمایشگاه بین‌المللی ارومیه">
    <link rel="icon" type="image/png" href="{% static 'images/fav-logo.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}{% endblock title %}</title>

    <link href="{% static 'css/plugins.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/rtl.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</head>
<body>
</head>

<body>

    <div class="body-inner">
        <header id="header" data-fullwidth="true" class="header-always-fixed">
            <div class="header-inner">
                <div class="container">
                    <div id="logo">
                        <a href="{% url 'office:home' %}">
                            <span class="logo-default">UIF</span>
                            <span class="logo-dark">UIF</span>
                        </a>
                    </div>
                        
                        
                    <div id="search"><a id="btn-search-close" class="btn-search-close" aria-label="Close search form"><i class="icon-x"></i></a>
                        <form class="search-form" action="search-results-page.html" method="get">
                            <input class="form-control" name="q" type="text" placeholder="جستجو کنید ..." />
                            <span class="text-muted">جستجو را شروع کنید و کلید "Enter" را بزنید یا برای خروج دکمه "ESC" را بزنید</span>
                        </form>
                    </div>
                        
                        
                    <div class="header-extras">
                        <ul>
                            <li>
                                <a id="btn-search" href="#"> <i class="icon-search"></i></a>
                            </li>
                            <li>
                                <div class="p-dropdown">
                                    <a href="#"><i class="icon-user-plus h4"></i></a>
                                    <ul class="p-dropdown-content text-center">
                                        <li><a href="{% url 'accounts:signout' %}"><i class="icon-log-out"></i>خروج</a>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                        
                        
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>

                    <div id="mainMenu" class="menu-center">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="{% url 'office:home' %}">خانه</a></li>
                                    <li class="dropdown"><a href="#">مشارکت کنندگان</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'office:customer-list' %}">لیست همه</a> </li>
                                            <li><a href="{% url 'office:customer-add' %}"> جدید</a> </li>
                                            <li><a href="{% url 'office:deactive-customer-list' %}">در انتظار تایید</a> </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown"><a href="#">نمایشگاه‌ها</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'office:exhibition-list' %}">لیست همه</a></li>
                                            <li><a href="{% url 'office:exhibition-add' %}">جدید</a></li>
                                            <li><a href="{% url 'office:request-list' %}">لیست درخواست‌ها</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu"><a href="#">مالی</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'office:payment-list' %}">رسید دریافت</a></li>
                                            <li class="dropdown-submenu">
                                                <a href="#">بیعانه‌ها</a>
                                                <ul class="dropdown-menu">
                                                    {% comment %} <li><a href="{% url 'office:deposit-list' %}">لیست همه</a></li>
                                                    <li><a href="{% url 'office:deposit-add' %}">جدید</a></li> {% endcomment %}
                                                </ul>

                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
        </header>
        {% block content %}{% endblock content %}
    </div>

    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>

    <script src="{% static 'js/functions.js' %}"></script>
    
  <!-- Include jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Include Select2 JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
   
{% block script %}{% endblock script %}
</body>

</html>